'use strict';

/**
 * scrape_shorts_trends.js
 *
 * Searches YouTube Shorts for competitor-intel queries, extracts transcripts/metadata via
 * Apify, and compiles a styled HTML -> PDF report via WeasyPrint.
 *
 * Actor note: "apify/youtube-scraper" does not exist on Apify. The verified, actively
 * maintained equivalent is "streamers/youtube-scraper" (88k+ users), which supports
 * keyword search + a Shorts-specific result cap + native view-count sorting + subtitle
 * download - confirmed against its real input schema before writing this script.
 *
 * Required environment variables (.env in this folder):
 *   APIFY_API_TOKEN - Apify API token
 *
 * Required local tooling (not npm packages):
 *   WeasyPrint (Python) + its system deps (Pango, GLib via Homebrew). On this machine the
 *   WeasyPrint console script is at WEASYPRINT_BIN below; macOS's System Integrity Protection
 *   strips DYLD_LIBRARY_PATH for signed system binaries like /usr/bin/python3, so invoking
 *   `python3 -m weasyprint` silently fails to find libgobject - the installed console script
 *   is not SIP-hardened the same way and works once DYLD_LIBRARY_PATH points at the Homebrew
 *   lib directory.
 */

require('dotenv').config();

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { ApifyClient } = require('apify-client');
const { brandConfig } = require('./config');

const ACTOR_ID = 'streamers/youtube-scraper';
const SEARCH_QUERIES = brandConfig.searchKeywords;
const MAX_SHORTS_PER_SEARCH = 20;
const TOP_OVERALL_COUNT = 20;

// Fonts are shared rendering infrastructure (not brand-specific), so they stay at the project
// root regardless of which brand's output folder the HTML/PDF land in.
const FONTS_DIR = path.join(__dirname, 'fonts');

const BRAND_DIR = path.join(__dirname, 'brands', brandConfig.folder);
fs.mkdirSync(BRAND_DIR, { recursive: true });
const HTML_OUTPUT_PATH = path.join(BRAND_DIR, 'Competitor_Viral_Shorts_Transcripts.html');
const PDF_OUTPUT_PATH = path.join(BRAND_DIR, 'Competitor_Viral_Shorts_Transcripts.pdf');

const WEASYPRINT_BIN = '/Users/tanyasingh/Library/Python/3.9/bin/weasyprint';
const HOMEBREW_LIB_DIR = '/opt/homebrew/lib';

function requireEnv(name) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}. Set it in a .env file in this folder.`);
  }
  return value;
}

function escapeHtml(value) {
  return (value ?? '')
    .toString()
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatNumber(n) {
  return typeof n === 'number' ? n.toLocaleString('en-US') : 'N/A';
}

// ---- Step 1: scrape ------------------------------------------------------------------------

async function scrapeShorts(client) {
  console.log(`Scraping YouTube Shorts via ${ACTOR_ID} for ${SEARCH_QUERIES.length} querie(s)...`);

  // NOTE: sortingOrder ('views') was tried and breaks the Shorts-only search path entirely -
  // it changes YouTube's encoded search URL filter and returns zero results for every query,
  // confirmed by testing. View-count sorting is instead done client-side below (renderTopOverallTable
  // and per-query sort in buildHtmlReport), which achieves the same result without the bug.
  const run = await client.actor(ACTOR_ID).call({
    searchQueries: SEARCH_QUERIES,
    maxResults: 0, // exclude regular long-form videos
    maxResultsShorts: MAX_SHORTS_PER_SEARCH,
    downloadSubtitles: true,
    subtitlesFormat: 'plaintext',
    preferAutoGeneratedSubtitles: true,
    subtitlesLanguage: 'any',
  });

  const { items } = await client.dataset(run.defaultDatasetId).listItems();

  const byQuery = new Map(SEARCH_QUERIES.map((q) => [q, []]));
  for (const item of items) {
    if (item.error) {
      console.log(`  No Shorts found for "${item.input}" (${item.error})`);
      continue;
    }
    const query = item.input || 'unknown';
    if (!byQuery.has(query)) byQuery.set(query, []);

    const transcript = Array.isArray(item.subtitles) && item.subtitles[0]?.plaintext
      ? item.subtitles[0].plaintext.trim()
      : null;

    byQuery.get(query).push({
      title: item.title || 'Untitled',
      channelName: item.channelName || 'Unknown channel',
      viewCount: typeof item.viewCount === 'number' ? item.viewCount : null,
      url: item.url || 'N/A',
      transcript,
      description: (item.text || '').trim(),
    });
  }

  return byQuery;
}

// ---- Step 2: HTML report --------------------------------------------------------------------

function renderVideoBlock(video, rank) {
  const transcriptBody = video.transcript
    ? escapeHtml(video.transcript).replace(/\n/g, '<br>')
    : `--- [Speech Transcript Unavailable / Visual Loop Only] ---<br><br>${escapeHtml(video.description) || '<em>No description available either.</em>'}`;

  return `
    <div class="video-card">
      <div class="video-rank">#${rank}</div>
      <div class="video-title">${escapeHtml(video.title)}</div>
      <div class="video-meta">
        Channel: <strong>${escapeHtml(video.channelName)}</strong> &nbsp;|&nbsp;
        Views: <strong>${formatNumber(video.viewCount)}</strong> &nbsp;|&nbsp;
        <a href="${escapeHtml(video.url)}">${escapeHtml(video.url)}</a>
      </div>
      <div class="transcript">${transcriptBody}</div>
    </div>
  `;
}

function renderTopOverallTable(allVideos) {
  const top = [...allVideos]
    .sort((a, b) => (b.viewCount ?? 0) - (a.viewCount ?? 0))
    .slice(0, TOP_OVERALL_COUNT);

  const rows = top
    .map((v, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${escapeHtml(v.title)}</td>
        <td>${escapeHtml(v.channelName)}</td>
        <td class="num">${formatNumber(v.viewCount)}</td>
        <td><a href="${escapeHtml(v.url)}">${escapeHtml(v.url)}</a></td>
      </tr>
    `)
    .join('');

  return `
    <table class="summary-table">
      <thead>
        <tr><th>#</th><th>Title</th><th>Channel</th><th>Views</th><th>URL</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  `;
}

function buildHtmlReport(byQuery) {
  const allVideos = [...byQuery.values()].flat();

  const querySections = [...byQuery.entries()]
    .map(([query, videos]) => {
      const sorted = [...videos].sort((a, b) => (b.viewCount ?? 0) - (a.viewCount ?? 0));
      const body = sorted.length > 0
        ? sorted.map((v, i) => renderVideoBlock(v, i + 1)).join('')
        : '<p class="empty-note">No Shorts results found for this query.</p>';

      return `
        <section class="query-block">
          <h2>Search term: "${escapeHtml(query)}"</h2>
          <p class="query-count">${sorted.length} result(s)</p>
          ${body}
        </section>
      `;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  /* Subtitles came back in Hindi, Tamil, Malayalam, and Gujarati (auto-generated by YouTube).
     Pango's automatic system-font fallback for these scripts produced a malformed embedded
     font for at least Gujarati (confirmed: pdftoppm threw "Embedded font file may be invalid"
     and that video's card silently failed to render, while pdftotext extraction still worked -
     two different code paths, so text-only checks don't catch this). Explicit static Noto
     fonts avoid relying on whichever font Pango happens to pick. */
  @font-face { font-family: 'NotoDevanagari'; src: url('file://${path.join(FONTS_DIR, 'NotoSansDevanagari-Regular.ttf')}'); }
  @font-face { font-family: 'NotoTamil'; src: url('file://${path.join(FONTS_DIR, 'NotoSansTamil-Regular.ttf')}'); }
  @font-face { font-family: 'NotoMalayalam'; src: url('file://${path.join(FONTS_DIR, 'NotoSansMalayalam-Regular.ttf')}'); }
  @font-face { font-family: 'NotoGujarati'; src: url('file://${path.join(FONTS_DIR, 'NotoSansGujarati-Regular.ttf')}'); }
  @font-face { font-family: 'NotoArabic'; src: url('file://${path.join(FONTS_DIR, 'NotoSansArabic-Regular.ttf')}'); }
  @page {
    size: A4;
    margin: 18mm 15mm;
    background-color: #fcfbfa;
    @top-center {
      content: "${brandConfig.displayName} Competitive Intel";
      font-size: 9px;
      color: #999;
    }
    @bottom-center {
      content: "Page " counter(page) " of " counter(pages);
      font-size: 9px;
      color: #999;
    }
  }
  body {
    font-family: Helvetica, NotoDevanagari, NotoTamil, NotoMalayalam, NotoGujarati, NotoArabic, Arial, sans-serif;
    color: #2b2b28;
    background-color: #fcfbfa;
    font-size: 11px;
    line-height: 1.5;
  }
  .banner {
    background-color: #2b3a2f;
    color: #fcfbfa;
    padding: 16px 20px;
    margin-bottom: 18px;
  }
  .banner h1 {
    margin: 0;
    font-size: 19px;
    letter-spacing: 0.5px;
  }
  .banner p {
    margin: 4px 0 0;
    font-size: 11px;
    color: #cdd6c9;
  }
  h2 {
    font-size: 14px;
    margin: 0 0 6px;
    color: #2b3a2f;
  }
  .summary-section {
    margin-bottom: 24px;
  }
  .summary-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 10px;
  }
  .summary-table th {
    text-align: left;
    background-color: #e7ece4;
    padding: 6px 8px;
    border-bottom: 1px solid #c7d0c2;
  }
  .summary-table td {
    padding: 6px 8px;
    border-bottom: 1px solid #ece9e4;
    overflow-wrap: break-word;
  }
  .summary-table td.num {
    text-align: right;
  }
  .query-block {
    background-color: #f1f3ef;
    border: 1px solid #dfe4da;
    border-radius: 4px;
    padding: 14px 16px;
    margin-bottom: 18px;
  }
  .query-count {
    font-size: 10px;
    color: #6b6f66;
    margin: 0 0 12px;
  }
  .video-card {
    background-color: #ffffff;
    border: 1px solid #e3e6e0;
    border-radius: 3px;
    padding: 10px 12px;
    margin-bottom: 10px;
  }
  .video-rank {
    display: inline-block;
    font-size: 9px;
    font-weight: bold;
    color: #6b8271;
    margin-bottom: 2px;
  }
  .video-title {
    font-size: 12px;
    font-weight: bold;
    margin-bottom: 4px;
  }
  .video-meta {
    font-size: 9px;
    color: #555;
    margin-bottom: 8px;
    word-break: break-all;
  }
  .video-meta a {
    color: #4a6b58;
  }
  .transcript {
    border-left: 3px solid #6b8271;
    padding-left: 10px;
    font-size: 10px;
    color: #333;
  }
  .empty-note {
    font-size: 10px;
    color: #888;
    font-style: italic;
  }
</style>
</head>
<body>
  <div class="banner">
    <h1>${brandConfig.displayName.toUpperCase()} COMPETITIVE INTEL &mdash; VIRAL SHORTS SCRIPT MATRIX</h1>
    <p>Generated ${new Date().toISOString().slice(0, 10)} &middot; ${allVideos.length} Shorts analyzed across ${byQuery.size} search querie(s)</p>
  </div>

  <section class="summary-section">
    <h2>Top ${TOP_OVERALL_COUNT} Shorts Overall (by view count)</h2>
    ${renderTopOverallTable(allVideos)}
  </section>

  ${querySections}
</body>
</html>`;
}

// ---- Step 3: PDF via WeasyPrint ---------------------------------------------------------------

function convertHtmlToPdf(htmlPath, pdfPath) {
  console.log('Converting HTML to PDF via WeasyPrint...');
  execFileSync(WEASYPRINT_BIN, [htmlPath, pdfPath], {
    env: { ...process.env, DYLD_LIBRARY_PATH: HOMEBREW_LIB_DIR },
    stdio: 'inherit',
  });
}

// ---- Orchestration ------------------------------------------------------------------------------

async function main() {
  const apifyToken = requireEnv('APIFY_API_TOKEN');
  const client = new ApifyClient({ token: apifyToken });

  const byQuery = await scrapeShorts(client);

  console.log('Building HTML report...');
  const html = buildHtmlReport(byQuery);
  fs.writeFileSync(HTML_OUTPUT_PATH, html);
  console.log(`Wrote ${HTML_OUTPUT_PATH}`);

  convertHtmlToPdf(HTML_OUTPUT_PATH, PDF_OUTPUT_PATH);
  console.log(`Done. PDF report: ${PDF_OUTPUT_PATH}`);
}

if (require.main === module) {
  main().catch((err) => {
    console.error('Failed:', err.message);
    process.exitCode = 1;
  });
}

module.exports = { buildHtmlReport, convertHtmlToPdf, HTML_OUTPUT_PATH, PDF_OUTPUT_PATH };
